name: pr-checks

on:
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: check node version
        run: node --version

      - name: simple script
        run: |
          echo "Pull Request detected."
          echo "Running lightweight checks..."
