name: day6-secrets-and-artifacts

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: use secret
        run: |
            echo "Secret length: ${#MY_SECRET_TOKEN}"
        env:
          MY_SECRET_TOKEN: ${{ secrets.MY_SECRET_TOKEN }}

      - name: create artifact file
        run: |
          mkdir output
          echo "Build timestamp: $(date)" > output/info.txt

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-info
          path: output/info.txt

  downstream:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-info

      - name: show artifact contents
        run: cat info.txt
